# -*- coding: utf-8 -*-
"""

Description: This script fits the ensemble member models on the underlying task (i.e. regression and classification) datasets.

Inputs:
    - run_machine: the machine used to run the code (e.g. 'local' or 'server' - governs the output directories etc.)
    - split_type: which type of data split is used for training ('kfold', 'bootstrap')
    - n_splits: the number of splits used for hyperparameter tuning (int)
    - fit_all_splits: whether a model should be fitted to all splits contained in the pickled ‘splits_[split_type]’ generated by the pipeline_step_1.py script (boolean)
    - model_type: the class of model to be fitted ('dnn', 'logistic_regression', 'regression', 'classification_tree', 'regression_tree', 'gradient_boosting_trees_classifier', 'gradient_boosting_trees_regressor')
    
Outputs:
    - For full dataset and if fit_all_splits=True then each split:
        - CSV of 'accs_underlying_random_[model_type]*[split_type]*[split_num]” and “accs_underlying_random_[model_type]_nosplit_all”
            - Train, val, and test accs on underlying task for learned model and a random model
        - CSV of 'y_hat_test_[split_type]_[split_num]' and 'y_hat_test_nosplit_all' ($\hat{p}$ not logits)
        - CSV of 'y_hat_train_[split_type]_[split_num]' and 'y_hat_train_nosplit_all' ($\hat{p}$ not logits)
        - CSV of 'y_hat_val_[split_type]_[split_num]' and 'y_hat_val_nosplit_all' ($\hat{p}$ not logits)
        - If sklearn model fitted: CSV of 'cv_results_[model_type]_[split_type]_[split_num]'
            - Pandas cv outputs (each hyperparameter setting and its scores across each fold and the averages and variances over each fold)
        - If tensorflow model fitted: CSV of 'training_losses_[split_type]_[split_num]'
    - If tensorflow model fitted: the name of the directory containing these files is 'dnn_opt_[optimizer_type]_sch_[lr_schedule]_lr_[init_lr]_wd_[wd]', for all other model types the directory is just '[model_type]'

python3 pipeline_step_2.py --run_machine='local' --model_type='logistic_regression' --n_splits=4 --split_type='kfold' --fit_all_splits=False > pipeline_step_2_outputs.txt

"""

###############################################################################

import os
from pathlib import Path
import pickle
from time import time
from tqdm import tqdm
import argparse

import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import RepeatedStratifiedKFold, RepeatedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression, Lasso
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingClassifier, GradientBoostingRegressor

from utils import get_superfix_prefix_and_make_dir
from utils_2 import get_loss_function, get_subsetted_tf_ds, get_optimizer, simpleSupervisedTrainTF

from data import get_dataset, get_batches_per_epoch_and_total_epochs

from models import TabWRN

###############################################################################

parser = argparse.ArgumentParser()

parser.add_argument('--run_machine', default='local', type=str, metavar='N', help="the machine used to run the code (e.g. 'local' or 'server' - governs the output directories etc)")
parser.add_argument('--model_type', default='logistic_regression', type=str, metavar='N', help="the class of underlying task model to be fitted ('dnn', 'logistic_regression', 'regression', 'classification_tree', 'regression_tree', 'gradient_boosting_trees_classifier', 'gradient_boosting_trees_regressor')")
parser.add_argument('--n_splits', default=4, type=int, metavar='N', help="the number of splits used for hyperparameter tuning (int)")
parser.add_argument('--split_type', default='kfold', type=str, metavar='N', help="which type of data split is used for training ('kfold', 'bootstrap')")
parser.add_argument('--fit_all_splits', default='False', type=str, metavar='N', help="whether a model should be fitted to all splits contained in the pickled ‘splits_[split_type]’ generated by the pipeline_step_1.py script (boolean)")

args = parser.parse_args()
run_machine = args.run_machine
model_types_list = [args.model_type]
n_splits = args.n_splits
split_type = args.split_type
fit_all_splits = args.fit_all_splits

###############################################################################

dataset_names_list = ['Wine',
'Phoneme',
'EyeMovements',
'Electricity',
'Jannis',
'MiniBooNE',
'Covertype',
'Pol',
'House16H',
'KDDIPUMS',
'MagicTelescope',
'Bank',
'Higgs',
'Credit',
'California',
'CPU_R',
'Pol_R',
'Elevators_R',
'Isolet_R',
'Wine_R',
'Ailerons_R',
'Houses_R',
'House16H_R',
'Diamonds_R',
'BrazilianHouses_R',
'BikeSharingDemand_R',
'NYCTaxi_R',
'HouseSales_R',
'Sulfur_R',
'MedicalCharges_R',
'MiamiHousing_R',
'Superconduct_R',
'California_R',
'Fifa_R',
'Year_R']

dnn_specific_params_list = [[0.0,'Adam',1e-5,'constant'],#1
                        [1e-7,'Adam',1e-5,'constant'],#2
                        [1e-5,'Adam',1e-5,'constant'],#3
                        [1e-3,'Adam',1e-5,'constant'],#4
                        [0.0,'Adam',1e-4,'constant'],##5
                        [1e-7,'Adam',1e-4,'constant'],#6
                        [1e-5,'Adam',1e-4,'constant'],#7
                        [1e-3,'Adam',1e-4,'constant'],#8
                        [0.0,'Adam',1e-3,'constant'],#9
                        [1e-7,'Adam',1e-3,'constant'],#10
                        [1e-5,'Adam',1e-3,'constant'],#11
                        [1e-3,'Adam',1e-3,'constant'],#12
                        [0.0,'SGD',1e-4,'cosine'],#13
                        [1e-7,'SGD',1e-4,'cosine'],#14
                        [1e-5,'SGD',1e-4,'cosine'],#15
                        [1e-3,'SGD',1e-4,'cosine'],#16
                        [0.0,'SGD',1e-3,'cosine'],#17
                        [1e-7,'SGD',1e-3,'cosine'],#18
                        [1e-5,'SGD',1e-3,'cosine'],#19
                        [1e-3,'SGD',1e-3,'cosine'],#20
                        [0.0,'SGD',1e-2,'cosine'],#21
                        [1e-7,'SGD',1e-2,'cosine'],#22
                        [1e-5,'SGD',1e-2,'cosine'],#23
                        [1e-3,'SGD',1e-2,'cosine']]#24

###############################################################################

def init_model(model_type,arch_hyper_dict):
    print('Warning (init_model): Categorical predictors are not supported')
    if model_type == 'classification_tree':
        model = DecisionTreeClassifier(random_state=0)
    elif model_type == 'logistic_regression':
        model = LogisticRegression(random_state=0,solver='saga',penalty='l1',max_iter=1e4)
    elif model_type == 'gradient_boosting_trees_classifier':
        model = GradientBoostingClassifier(random_state=0)
    elif model_type == 'regression_tree':
        model = DecisionTreeRegressor(random_state=0)
    elif model_type == 'regression':
        model = Lasso(random_state=0,selection='random',max_iter=1e4)
    elif model_type == 'gradient_boosting_trees_regressor':
        model = GradientBoostingRegressor(random_state=0)
    elif model_type == 'dnn':
        model = TabWRN(output_size=arch_hyper_dict.get('pred_dim'),
                       with_top=True,
                       num_base_nodes=arch_hyper_dict.get('n_base_nodes'),
                       N=arch_hyper_dict.get('N'),
                       k=arch_hyper_dict.get('k'),
                       drop_p=arch_hyper_dict.get('drop_p'),
                       weight_decay=arch_hyper_dict.get('weight_decay'),
                       categorical_features_indicator_dict=arch_hyper_dict.get('categorical_features_indicator_dict'),
                       categorical_features_vocabulary_size_dict=arch_hyper_dict.get('categorical_features_vocabulary_size_dict'),
                       embedding_output_dim=arch_hyper_dict.get('embedding_output_dim'))
    else:
        raise ValueError('init_model: This model_arch not implemented')
    
    return model
    


def supervised_tune_and_train(prefix,model,model_type,ds_dict,pred_dim_underlying,train_split,split_type,split_i,loss_fn,opt,batch_size=64,epochs=400,save_name_params={}):
    ds_sklearn = ds_dict.get('ds_sklearn')
    ds_tensorflow = ds_dict.get('ds_tensorflow')
    
    problem_type = ds_dict.get('problem_type')
    
    train_index = train_split[1]
    
    if model_type == 'dnn':
        dir_model = os.path.join(prefix,model_type+'_opt_'+save_name_params.get('opt')+'_sch_'+save_name_params.get('sch')+'_lr_'+save_name_params.get('lr')+'_wd_'+save_name_params.get('wd'))
        Path(dir_model).mkdir(parents=True, exist_ok=True)
    else:
        dir_model = os.path.join(prefix,model_type)
        Path(dir_model).mkdir(parents=True, exist_ok=True)
    
    if model_type == 'dnn':
        print('Fitting tf_dnn...')
        start_time = time()
        
        tf_ds_train_subset = get_subsetted_tf_ds(ds_sk=ds_sklearn.get('ds_train'),idx=train_index,categorical_indicator=ds_dict.get('categorical_indicator'),embeddings=ds_dict.get('embeddings_tf'),problem_type=problem_type)
        
        model = simpleSupervisedTrainTF(model=model,
                                        train_dataset=tf_ds_train_subset,
                                        val_dataset=ds_tensorflow.get('ds_val'),
                                        test_dataset=ds_tensorflow.get('ds_test'),
                                        batch_size=batch_size,epochs=epochs,
                                        loss_fn=loss_fn,opt=opt,
                                        prefix=os.path.join(dir_model,'training_losses_'+str(split_type)+'_'+str(split_i)+'_'))
        print('----------\nFitting complete\n','duration:',np.round((time()-start_time)/60,2),'min')
        
    elif model_type == 'classification_tree':
        print('Tuning sklearn_classification_tree...')
        start_time = time()
        param_grid = {'max_depth':[2**i for i in range(1,12)],
                      'min_samples_split':[2**i for i in range(1,12)],
                      'max_leaf_nodes':[2**i for i in range(1,12)]}
        base_estimator = DecisionTreeClassifier()
        cv_folds = RepeatedStratifiedKFold(n_splits=n_splits,n_repeats=1,random_state=0)
        grid_search = GridSearchCV(estimator=base_estimator,param_grid=param_grid,n_jobs=-1,cv=cv_folds,scoring='accuracy',verbose=1)
        search_results = grid_search.fit(X=np.take(ds_sklearn.get('ds_train').get('x_train'),train_index,0),y=np.take(ds_sklearn.get('ds_train').get('y_train'),train_index,0))
        wb = search_results.best_estimator_
        print('----------\nTuning complete\nbest estimator:',wb,'\n','cv acc:',np.round(search_results.best_score_*100,2),'\n','duration:',np.round((time()-start_time)/60,2),'min')
        pd.DataFrame.from_dict(search_results.cv_results_).to_csv(os.path.join(prefix,model_type,'cv_results_classification_tree_'+str(split_type)+'_'+str(split_i)+'.csv'))
    elif model_type == 'logistic_regression':
        print('Tuning sklearn_logistic_regression...')
        start_time = time()
        param_grid = {'C':[2**i for i in range(-10,10,1)]}
        base_estimator = LogisticRegression(random_state=0,solver='saga',penalty='l1',max_iter=1e4) 
        cv_folds = RepeatedStratifiedKFold(n_splits=n_splits,n_repeats=1,random_state=0)
        grid_search = GridSearchCV(estimator=base_estimator,param_grid=param_grid,n_jobs=-1,cv=cv_folds,scoring='accuracy',verbose=1)
        search_results = grid_search.fit(X=np.take(ds_sklearn.get('ds_train').get('x_train'),train_index,0),y=np.take(ds_sklearn.get('ds_train').get('y_train'),train_index,0))
        wb = search_results.best_estimator_
        print('----------\nTuning complete\nbest estimator:',wb,'\n','cv acc:',np.round(search_results.best_score_*100,2),'\n','duration:',np.round((time()-start_time)/60,2),'min')
        pd.DataFrame.from_dict(search_results.cv_results_).to_csv(os.path.join(prefix,model_type,'cv_results_logisitic_regression_'+str(split_type)+'_'+str(split_i)+'.csv'))
    elif model_type == 'gradient_boosting_trees_classifier':
        print('Tuning sklearn_gradient_boosting_trees_classifier...')
        start_time = time()
        param_grid = {'learning_rate':[10**i for i in range(-3,0,1)], 
                      'n_estimators':[2**i for i in range(4,10,1)], 
                      'max_depth':[2**i for i in range(3,7,1)], 
                      'subsample':[2e-1*i for i in range(1,6,1)]} 
        base_estimator = GradientBoostingClassifier(random_state=0)
        cv_folds = RepeatedStratifiedKFold(n_splits=n_splits,n_repeats=1,random_state=0)
        grid_search = GridSearchCV(estimator=base_estimator,param_grid=param_grid,n_jobs=-1,cv=cv_folds,scoring='accuracy',verbose=1)
        search_results = grid_search.fit(X=np.take(ds_sklearn.get('ds_train').get('x_train'),train_index,0),y=np.take(ds_sklearn.get('ds_train').get('y_train'),train_index,0))
        wb = search_results.best_estimator_
        print('----------\nTuning complete\nbest estimator:',wb,'\n','cv acc:',np.round(search_results.best_score_*100,2),'\n','duration:',np.round((time()-start_time)/60,2),'min')
        pd.DataFrame.from_dict(search_results.cv_results_).to_csv(os.path.join(prefix,model_type,'cv_results_gradient_boosting_trees_classifier_'+str(split_type)+'_'+str(split_i)+'.csv'))
    elif model_type == 'regression_tree':
        print('Tuning sklearn_regression_tree...')
        start_time = time()
        param_grid = {'max_depth':[2**i for i in range(1,12)],
                      'min_samples_split':[2**i for i in range(1,12)],
                      'max_leaf_nodes':[2**i for i in range(1,12)]}
        base_estimator = DecisionTreeRegressor()
        cv_folds = RepeatedKFold(n_splits=n_splits,n_repeats=1,random_state=0)
        grid_search = GridSearchCV(estimator=base_estimator,param_grid=param_grid,n_jobs=-1,cv=cv_folds,scoring='neg_mean_squared_error',verbose=1)
        search_results = grid_search.fit(X=np.take(ds_sklearn.get('ds_train').get('x_train'),train_index,0),y=np.take(ds_sklearn.get('ds_train').get('y_train'),train_index,0))
        wb = search_results.best_estimator_
        print('----------\nTuning complete\nbest estimator:',wb,'\n','cv acc:',np.round(search_results.best_score_*100,2),'\n','duration:',np.round((time()-start_time)/60,2),'min')
        pd.DataFrame.from_dict(search_results.cv_results_).to_csv(os.path.join(prefix,model_type,'cv_results_regression_tree_'+str(split_type)+'_'+str(split_i)+'.csv'))
    elif model_type == 'regression':
        print('Tuning sklearn_regression...')
        start_time = time()
        param_grid = {'alpha':[2**i for i in range(-10,10,1)]}
        base_estimator = Lasso(random_state=0,selection='random',max_iter=1e4) 
        cv_folds = RepeatedKFold(n_splits=n_splits,n_repeats=1,random_state=0)
        grid_search = GridSearchCV(estimator=base_estimator,param_grid=param_grid,n_jobs=-1,cv=cv_folds,scoring='neg_mean_squared_error',verbose=1)
        search_results = grid_search.fit(X=np.take(ds_sklearn.get('ds_train').get('x_train'),train_index,0),y=np.take(ds_sklearn.get('ds_train').get('y_train'),train_index,0))
        wb = search_results.best_estimator_
        print('----------\nTuning complete\nbest estimator:',wb,'\n','cv acc:',np.round(search_results.best_score_*100,2),'\n','duration:',np.round((time()-start_time)/60,2),'min')
        pd.DataFrame.from_dict(search_results.cv_results_).to_csv(os.path.join(prefix,model_type,'cv_results_regression_'+str(split_type)+'_'+str(split_i)+'.csv'))
    elif model_type == 'gradient_boosting_trees_regressor':
        print('Tuning sklearn_gradient_boosting_trees_regressor...')
        start_time = time()
        param_grid = {'learning_rate':[10**i for i in range(-3,0,1)], 
                      'n_estimators':[2**i for i in range(4,10,1)], 
                      'max_depth':[2**i for i in range(3,7,1)], 
                      'subsample':[2e-1*i for i in range(1,6,1)]} 
        base_estimator = GradientBoostingRegressor(random_state=0)
        cv_folds = RepeatedKFold(n_splits=n_splits,n_repeats=1,random_state=0)
        grid_search = GridSearchCV(estimator=base_estimator,param_grid=param_grid,n_jobs=-1,cv=cv_folds,scoring='neg_mean_squared_error',verbose=1)
        search_results = grid_search.fit(X=np.take(ds_sklearn.get('ds_train').get('x_train'),train_index,0),y=np.take(ds_sklearn.get('ds_train').get('y_train'),train_index,0))
        wb = search_results.best_estimator_
        print('----------\nTuning complete\nbest estimator:',wb,'\n','cv acc:',np.round(search_results.best_score_*100,2),'\n','duration:',np.round((time()-start_time)/60,2),'min')
        pd.DataFrame.from_dict(search_results.cv_results_).to_csv(os.path.join(prefix,model_type,'cv_results_gradient_boosting_trees_regressor_'+str(split_type)+'_'+str(split_i)+'.csv'))
    else:
        raise ValueError('supervised_tune_and_train: This model_type not implemented')
    
    if model_type == 'dnn':
        y_hat_train = []
        for step,(x_i,y_i) in enumerate(tqdm(ds_tensorflow.get('ds_train').batch(batch_size))):
            y_hat_i = model(x_i,training=False)
            y_hat_train.append(y_hat_i)
        
        y_hat_val = []
        for step,(x_i,y_i) in enumerate(tqdm(ds_tensorflow.get('ds_val').batch(batch_size))):
            y_hat_i = model(x_i,training=False)
            y_hat_val.append(y_hat_i)
        
        y_hat_test = []
        for step,(x_i,y_i) in enumerate(tqdm(ds_tensorflow.get('ds_test').batch(batch_size))):
            y_hat_i = model(x_i,training=False)
            y_hat_test.append(y_hat_i)
        
        if problem_type == 'classification':
            y_hat_train = tf.nn.softmax(tf.concat(y_hat_train,0)).numpy()
            y_hat_val = tf.nn.softmax(tf.concat(y_hat_val,0)).numpy()
            y_hat_test = tf.nn.softmax(tf.concat(y_hat_test,0)).numpy()
        elif problem_type == 'regression':
            y_hat_train = tf.concat(y_hat_train,0).numpy()
            y_hat_val = tf.concat(y_hat_val,0).numpy()
            y_hat_test = tf.concat(y_hat_test,0).numpy()
        else:
            raise ValueError('supervised_tune_and_train: This problem_type is not implemented')
    else:
        if problem_type == 'classification':
            y_hat_train = wb.predict_proba(X=ds_sklearn.get('ds_train').get('x_train'))
            y_hat_val = wb.predict_proba(X=ds_sklearn.get('ds_val').get('x_val'))
            y_hat_test = wb.predict_proba(X=ds_sklearn.get('ds_test').get('x_test'))
        elif problem_type == 'regression':
            y_hat_train = wb.predict(X=ds_sklearn.get('ds_train').get('x_train'))
            y_hat_val = wb.predict(X=ds_sklearn.get('ds_val').get('x_val'))
            y_hat_test = wb.predict(X=ds_sklearn.get('ds_test').get('x_test'))
            if len(y_hat_train.shape)==1:
                y_hat_train = np.expand_dims(y_hat_train,-1)
                y_hat_val = np.expand_dims(y_hat_val,-1)
                y_hat_test = np.expand_dims(y_hat_test,-1)
        else:
            raise ValueError('supervised_tune_and_train: This problem_type is not implemented')
        
    pred_dim = y_hat_train.shape[1]
    pd_y_hat_train = pd.DataFrame(y_hat_train,columns=['y_hat_'+str(i) for i in range(pred_dim)])
    pd_y_hat_val = pd.DataFrame(y_hat_val,columns=['y_hat_'+str(i) for i in range(pred_dim)])
    pd_y_hat_test = pd.DataFrame(y_hat_test,columns=['y_hat_'+str(i) for i in range(pred_dim)])
    
    pd_y_hat_train.to_csv(os.path.join(dir_model,'y_hat_train_'+str(split_type)+'_'+str(split_i)+'.csv'))
    pd_y_hat_val.to_csv(os.path.join(dir_model,'y_hat_val_'+str(split_type)+'_'+str(split_i)+'.csv'))
    pd_y_hat_test.to_csv(os.path.join(dir_model,'y_hat_test_'+str(split_type)+'_'+str(split_i)+'.csv'))
    
    #--------------------------------------------------------------------------
        
    if problem_type == 'classification':
        y_train = ds_sklearn.get('ds_train').get('y_train').astype(np.int32)
        y_val = ds_sklearn.get('ds_val').get('y_val').astype(np.int32)
        y_test = ds_sklearn.get('ds_test').get('y_test').astype(np.int32)
        
        y_train = np.eye(pred_dim_underlying)[y_train].astype(np.float32)
        y_val = np.eye(pred_dim_underlying)[y_val].astype(np.float32)
        y_test = np.eye(pred_dim_underlying)[y_test].astype(np.float32)
        
        acc_random_train = np.max(np.mean(y_train,0))*100
        acc_train = np.mean(np.argmax(y_train,1)==np.argmax(y_hat_train,1))*100
        
        acc_random_val = np.max(np.mean(y_val,0))*100
        acc_val = np.mean(np.argmax(y_val,1)==np.argmax(y_hat_val,1))*100
        
        acc_random_test = np.max(np.mean(y_test,0))*100
        acc_test = np.mean(np.argmax(y_test,1)==np.argmax(y_hat_test,1))*100
        
        print('\naccuracies: train (random,wb)', np.round(acc_random_train,2), np.round(acc_train,2))
        print('accuracies: val (random,wb)', np.round(acc_random_val,2), np.round(acc_val,2))
        print('accuracies: test (random,wb)', np.round(acc_random_test,2), np.round(acc_test,2))
        
        pd_acc = pd.DataFrame([[acc_random_train, acc_train],
                               [acc_random_val, acc_val],
                               [acc_random_test, acc_test]],
                              index=['train_ds','val_ds','test_ds'],
                              columns=['random_underlying_acc','model_underlying_acc'])
        
        pd_acc.to_csv(os.path.join(dir_model,'accs_underlying_random_'+model_type+'_'+str(split_type)+'_'+str(split_i)+'.csv'))
    elif problem_type == 'regression':
        y_train = ds_sklearn.get('ds_train').get('y_train').astype(np.float32)
        y_val = ds_sklearn.get('ds_val').get('y_val').astype(np.float32)
        y_test = ds_sklearn.get('ds_test').get('y_test').astype(np.float32)
        
        if len(y_train.shape)==1:
            y_train = np.expand_dims(y_train,-1)
            y_val = np.expand_dims(y_val,-1)
            y_test = np.expand_dims(y_test,-1)
        
        error_random_train = np.sqrt(np.mean(np.sum((y_train[np.random.permutation(y_train.shape[0])]-y_train)**2,1),0)+1e-7)
        error_train = np.sqrt(np.mean(np.sum((y_train-y_hat_train)**2,1),0)+1e-7)
        
        error_random_val = np.sqrt(np.mean(np.sum((y_val[np.random.permutation(y_val.shape[0])]-y_val)**2,1),0)+1e-7)
        error_val = np.sqrt(np.mean(np.sum((y_val-y_hat_val)**2,1),0)+1e-7)
        
        error_random_test = np.sqrt(np.mean(np.sum((y_test[np.random.permutation(y_test.shape[0])]-y_test)**2,1),0)+1e-7)
        error_test = np.sqrt(np.mean(np.sum((y_test-y_hat_test)**2,1),0)+1e-7)
        
        print('\nerrors: train (random,wb)', np.round(error_random_train,2), np.round(error_train,2))
        print('errors: val (random,wb)', np.round(error_random_val,2), np.round(error_val,2))
        print('errors: test (random,wb)', np.round(error_random_test,2), np.round(error_test,2))
        
        pd_acc = pd.DataFrame([[error_random_train, error_train],
                               [error_random_val, error_val],
                               [error_random_test, error_test]],
                              index=['train_ds','val_ds','test_ds'],
                              columns=['random_underlying_rmse','model_underlying_rmse'])
        
        pd_acc.to_csv(os.path.join(dir_model,'errors_underlying_random_'+model_type+'_'+str(split_type)+'_'+str(split_i)+'.csv'))
    else:
        raise ValueError('supervised_tune_and_train: This problem_type is not implemented')
        
    #--------------------------------------------------------------------------

def pipeline_step_2(model_type,n_splits,split_type,fit_all_splits,run_machine,experiment_name,dataset_name,
                    wd,optimizer_type,init_lr,lr_schedule,momentum,batch_size):
    start_time = time()
    
    if model_type == 'dnn':
        batches_per_epoch,epochs = get_batches_per_epoch_and_total_epochs(dataset_name=dataset_name,batch_size=batch_size)
        decay_steps = epochs*batches_per_epoch
    else:
        batches_per_epoch,epochs,decay_steps = None,None,None
    
    dir_superfix,dir_prefix = get_superfix_prefix_and_make_dir(run_machine=run_machine,experiment_name=experiment_name,overwrite_check=False)
    
    pred_dim_underlying,ds_dict = get_dataset(dataset_name=dataset_name) 
    
    if fit_all_splits:
        with open(os.path.join(dir_prefix,'data_splits','splits_'+split_type), 'rb') as f:
            splits = pickle.load(f)
        
        for split_i in range(n_splits):
            
            model = init_model(model_type=model_type,
                               arch_hyper_dict={'pred_dim':pred_dim_underlying,'n_base_nodes':16,'N':4,'k':2,'drop_p':0.0,'weight_decay':wd,
                                                'categorical_features_indicator_dict':ds_dict.get('categorical_indicator'),
                                                'categorical_features_vocabulary_size_dict':ds_dict.get('categorical_vocabulary_size_tensorflow'),
                                                'embedding_output_dim':1})
            if model_type == 'dnn':
                loss_fn = get_loss_function(problem_type=ds_dict.get('problem_type'))
                opt = get_optimizer(optimizer_type=optimizer_type,momentum=momentum,init_lr=init_lr,lr_schedule=lr_schedule,decay_steps=decay_steps)
            else:
                loss_fn,opt = None,None
            
            train_split = splits[split_i]
            supervised_tune_and_train(prefix=dir_prefix,model_type=model_type,model=model,ds_dict=ds_dict,pred_dim_underlying=pred_dim_underlying,
                                      train_split=train_split,split_type=split_type,split_i=split_i,
                                      batch_size=batch_size,epochs=epochs,loss_fn=loss_fn,opt=opt,
                                      save_name_params={'wd':str(wd),'opt':optimizer_type,'lr':str(init_lr),'sch':lr_schedule})
            
    model = init_model(model_type=model_type,
                       arch_hyper_dict={'pred_dim':pred_dim_underlying,'n_base_nodes':16,'N':4,'k':2,'drop_p':0.0,'weight_decay':wd,
                                        'categorical_features_indicator_dict':ds_dict.get('categorical_indicator'),
                                        'categorical_features_vocabulary_size_dict':ds_dict.get('categorical_vocabulary_size_tensorflow'),
                                        'embedding_output_dim':1})
    
    if model_type == 'dnn':
        loss_fn = get_loss_function(problem_type=ds_dict.get('problem_type'))
        opt = get_optimizer(optimizer_type=optimizer_type,momentum=momentum,init_lr=init_lr,lr_schedule=lr_schedule,decay_steps=decay_steps)
    else:
        loss_fn,opt = None,None
    
    n_train = ds_dict.get('ds_sklearn').get('ds_train').get('x_train').shape[0]
    train_split = tuple((np.arange(n_train,dtype=np.int32),np.arange(n_train,dtype=np.int32)))
    save_name_params={'wd':str(wd),'opt':optimizer_type,'lr':str(init_lr),'sch':lr_schedule}
    supervised_tune_and_train(prefix=dir_prefix,model_type=model_type,model=model,ds_dict=ds_dict,pred_dim_underlying=pred_dim_underlying,
                              train_split=train_split,split_type='nosplit',split_i='all',
                              batch_size=batch_size,epochs=epochs,loss_fn=loss_fn,opt=opt,
                              save_name_params=save_name_params)
    
    end_time = time()
    run_time = np.round((end_time-start_time)/60,2)
    print('total runtime (min):', run_time)
    
    if model_type == 'dnn':
        dir_model = os.path.join(dir_prefix,model_type+'_opt_'+save_name_params.get('opt')+'_sch_'+save_name_params.get('sch')+'_lr_'+save_name_params.get('lr')+'_wd_'+save_name_params.get('wd'))
    else:
        dir_model = os.path.join(dir_prefix,model_type)
    
    pd.DataFrame([[run_time]],columns=['total_run_time_min']).to_csv(os.path.join(dir_model,'pipeline_step_2_total_run_time.csv'))

###############################################################################

for dataset_name in dataset_names_list:
    experiment_name = 'Exp_'+dataset_name
    for model_type in model_types_list:
        if model_type == 'dnn':
            for dnn_specific_params in dnn_specific_params_list:
                wd = dnn_specific_params[0]
                optimizer_type = dnn_specific_params[1]
                init_lr = dnn_specific_params[2]
                lr_schedule = dnn_specific_params[3]
                momentum = 0.9
                batch_size = 64
                
                pipeline_step_2(model_type=model_type,n_splits=n_splits,split_type=split_type,
                                fit_all_splits=fit_all_splits,run_machine=run_machine,
                                experiment_name=experiment_name,dataset_name=dataset_name,wd=wd,
                                optimizer_type=optimizer_type,init_lr=init_lr,
                                lr_schedule=lr_schedule,momentum=momentum,batch_size=batch_size)
        else:
            pipeline_step_2(model_type=model_type,n_splits=n_splits,split_type=split_type,
                                fit_all_splits=fit_all_splits,run_machine=run_machine,
                                experiment_name=experiment_name,dataset_name=dataset_name,wd=None,
                                optimizer_type=None,init_lr=None,
                                lr_schedule=None,momentum=None,batch_size=None)




